### ISSUE TITLE
website contents should be open-sourced

### ISSUE THREAD

**Issue by kubukoz** [propensive/fury-old#117]
Can you publish the source for the website, so that we can submit changes to it?

~I think the getting started page (https://fury.build/getting-started) should say "fury init" instead of "fury layer init" (in 0.3.0), and I wanted to fix this :P~

I was wrong, it was a leftover of a previous installation.

**Comment by PawelLipski** [comment]
No longer relevant, closing

**Comment by kubukoz** [comment]
Actually, the website's repo is still hidden :p

**Comment by ArturGajowy** [comment]
I think the issue was actually about the website repo, not the not-a-bug in the docs themselves which @kubukoz was going to open a PR for. I guess opening that repo for PRs makes sense if you guys want the community to contribute to the docs :) I guess it's OK if you don't want that, but it's better stated explicitly :)

**Comment by PawelLipski** [comment]
Okay, sorry, I missed the point of the ticket ;)

**Comment by propensive** [comment]
Yep, the Fury website is currently in the same repository mixed up various other of my websites. I'm going to separate them out this week so that I can let you edit the Fury site without giving you access to the payment processing on the Scala World website. ;)

**Comment by propensive** [comment]
I've closed this without fixing it. There's a bigger project to sort out my website(s) and Fury documentation.
