### ISSUE TITLE
The fat JAR includes META-INF contents from dependency JARs

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1197]
In particular, the JAR build for Fury contains manifest signatures from some other JAR. This [causes](https://stackoverflow.com/questions/999489/invalid-signature-file-when-attempting-to-run-a-jar#6743609) errors during installation.

**Comment by propensive** [comment]
I made a change recently to perform classpath-equivalent "shadowing" of identically-named files when constructing the fat JAR, as I was getting some "duplicate entry" errors when constructing the JAR. I didn't change the rule to skip all `META-INF` entries, though, so I'm not sure why this has come from.

#1198 looks like it is intended to just accept these files will be present, rather than remove them. Is that right?

**Comment by odisseus** [comment]
PR #1198 is just a workaround to make the current bootstrapping version usable.

**Comment by propensive** [comment]
I think this problem went away, didn't it?

**Comment by odisseus** [comment]
So it seems, but I think this issue needs further investigation. It looks like there are some conditions, when Fury would package leftovers of other builds into the fat JAR.

**Comment by propensive** [comment]
Yes, I think there's still something strange going on there.

**Comment by propensive** [comment]
Having said that, I'm happy that the main problem is fixed, and we shouldn't see zipfile errors again, so I'm going to close this.
