### ISSUE TITLE
make it possible to skip parameters when the target of an action is obvious

### ISSUE THREAD

**Issue by PawelLipski** [propensive/fury-old#127]
Originally suggested by @marek1840, I second that suggestion.

E.g. `fury project select --project shapeless` could as well be `fury project select shapeless`, `fury import add -i .scala:scala-2.13.0-M5` could be `fury import add .scala:scala-2.13.0-M5` etc.

**Comment by propensive** [comment]
I've wondered about this, and it's been mentioned before because it's quite common (at least if you're not familiar with Fury) to forget the parameters, and to be surprise when it doesn't work. It's also possible, though, to get a bit trigger-happy with tab-completion and have it complete parameters when you don't want it to.

Given that I don't want to enable this for every command, I quite like the universal fact that every parameter must be prefixed with a `--` flag indicating what it is, and there is no positional significance in Fury commands.

That doesn't mean I'm completely fixated on the idea. So I'd like to leave this open a bit longer, and invite more feedback on what users think. I'll accept any convincing argument which shows that nothing bad can ever come from overzealous tab-completion, and that having a mixture of positional and named parameters is never confusing.

The more I think about it, the more I can believe it could be more intuitive...

**Comment by mzarnowski** [comment]
It is easier and more intuitive to write:
`fury module add foo` than `fury module add --name foo`

This gets a bit interesting, when trying to use with other attributes (e.g. `fury module add --name foo --project bar --compiler baz`) but I believe that inferring `--name` when there are no other attributes covers the most common and most intuitive use case. 

When there are other attributes, we could still require it for now - or just think on this case a bit longer, to see what is most intuitive.

**Comment by propensive** [comment]
I'm going to close this, but there's a bigger task to improve tab-completion in a few different ways. I'll create separate new issues for those enhancements.
