### ISSUE TITLE
The makefile produces a broken distribution when certain servers are down

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1297]
The makefile tries to download a Nailgun launch script from https://raw.githubusercontent.com/facebook/nailgun/master/nailgun-client/py/ng.py. When that server returns a 500 error, the launcher file is nevertheless written, and the build or installation continues. Unfortunately, the resulting distribution is unable to start.

The corrupted launcher script looks like this:
```
500: Internal Server Error2.7
```

**Comment by propensive** [comment]
Ouch. I've noticed also that if compilation fails, certain build operations continue regardless. I think this is because we usually print error messages in the event of a failure, but doing so rectifies the nonzero exit code. Adding `&& exit 1` to the end of every failure message might be a good start to fixing this particular issue, though maybe not so much the one described above.
