### ISSUE TITLE
don't write a `.done` file to indicate cloning is complete

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1436]
Instead delete a .not-done file if it's not.

**Comment by veyga** [comment]
@propensive 
Can you clarify what you mean by this, delete a .not-done file. I was not aware this file is ever created.

Does this done file act as a sort of lock? If not, then it seems this issue resolution is a one-liner.

**Comment by odisseus** [comment]
There is no such file at the moment.

The current way to check whether a repository has been successfully cloned and cached is looking for a `.done` file in its cache directory. Fury creates that file after the cloning operation is complete. 

I guess the goal of this story is to switch to the opposite approach: create a marker file named `.not-done` before the cloning starts, and remove that file after it is finished.

A potential problem is the situation when there is an empty cache directory, but Fury failed to create even the marker file (perhaps due to lack of filesystem permissions). You can tell this situation apart by checking whether there are files [typical of](https://www.siteground.com/tutorials/git/directory-structure/) a [bare](https://stackoverflow.com/a/2200662) Git repository, such as `HEAD` or `refs`.

**Comment by propensive** [comment]
Sorry, the description was very brief because I wanted to set a reminder for myself, rather than risk forgetting it. But @odisseus's clarification is correct. I see these `.done` files occasionally, but it's a rather crude way of testing whether a git checkout failed.
