### ISSUE TITLE
consider changing configuration file format

### ISSUE THREAD

**Issue by kubukoz** [propensive/fury-old#150]
For non-trivial projects, I think the ogdl format is going to quickly get old. Especially if there are merge conflicts to resolve 😨 . Please consider using yaml/something else instead :)

**Comment by propensive** [comment]
I'm going to think about it some more.

There are some features I like about the current format, such as having a unique serialization (i.e. one-to-one) of any given build. The diffs that OGDL produces should be very readable, but merges and rebases are likely to be problematic... but I'm not sure that YAML would be much better in this respect.

I wonder whether there's a way for Fury to manage merges and rebases. It can already produce a "diff" between any two case-class structures, and it wouldn't be impossible to reconstruct modification commands from those diffs.

Regarding the file format, I've got plans to automigrate files whenever the format changes. This would be done incrementally, version-by-version, between the OGDL being parsed into its dynamic, string-based format, and being deserialized into case classes. I *think* this will be easier with the simple OGDL format, but I can be convinced otherwise... In the event that a later file format needs more information to be specified than an earlier format, Fury would substitute some sort of default value for those cases, but emit warnings to tell the user to check/fix them afterwards.

**Comment by propensive** [comment]
@kubukoz I'm going to move away from line-based/VCS merging. I had a discussion with @marek1840 and @tpasternak today about how merges could work, and I think we have a better (semantic) solution. More information to follow. :)
