### ISSUE TITLE
do more logging

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#167]
Logs should be generated for every run of Fury, and stored in the `.fury/logs` directory. The amount of information logged should be configurable.

**Comment by tpasternak** [comment]
If logs are going to be always redirected to file and the loglevel is going to configurable, it's also good to log current loglevel. If we don't do this, we'll end up with a file with logs of mixed loglevels, so if something will be missing, we will not know if it's caused by low loglevel or some bug in the application.

**Comment by odisseus** [comment]
I think that the files should always contain the most detailed logs. On the other hand, the amount of console output should be configurable — for example, the user would pass a flag for "quiet mode" or another one for "verbose mode".
