### ISSUE TITLE
the integrity of repositories is not checked

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#534]
### Steps to reproduce
1. Check out any project that has many source dependencies, e. g. Fury itself
2. Locate the directory where Fury checks out the external repositories (most likely `~/.furyrc`)
3. Run `fury` to make sure that the build passes.
4. Remove some source files from the repositories managed by Fury:
```
find ~/.furyrc -name '*a*.scala' -delete
```
5. Rebuild the project

**Expected result:** the managed repositories are restored to their unmodified state, ad the project is successfully built.
**Actual result:** There are compilation errors due to missing source files.

As far as I know, there is no easy way to restore the repositories for transitive source dependencies except dumping all repository data with `fury clean sources`.

**Comment by propensive** [comment]
I'm not sure what the best solution for this is. Basically you shouldn't be modifying anything inside `.furyrc` directly, but it would be easy to do so. We could do a `git status` on each checkout to make sure it's clean, but the cost of that might be prohibitive, and I'd like to avoid it if possible.

This is true of repos checked out in `.furyrc`, but should not be true of local source directories. We should calculate the hash of all their sources, because they're not managed by Fury, and are expected to change frequently.
