### ISSUE TITLE
cannot reset a module's compiler to `java/compiler`

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#542]
If the module is currently set to `scala/compiler` and you try to change it to `java/compiler`, the error reported is:
```
The module reference java/compiler could not be resolved.
```

**Comment by odisseus** [comment]
That's expected, because your project likely doesn't contain a module called "java/compiler". 

Unsetting the compiler altogether should result in Bloop using the default Java compiler (whatever it may be) to compile the module in question. However, this currently cannot be achieved through the command line.

Here is the way that actually works:
1. Create an empty module marked as compiler:
`fury module add -n dummy-compiler -t compiler`
2. Use it as a compiler reference in the modules that should be built with the default compiler:
`fury module update -m my-module -c dummy-compiler`
