### ISSUE TITLE
old errors are displayed when running Fury in "watch" mode at the same time as Metals

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#883]
Old error messages from previous failed compilations seem to get cached between build runs, and displayed even when compilation is successful. I suspect that this happens with modules whose compilation is deduplicated because Metals compiles them first.

**Comment by odisseus** [comment]
The trick with creating a new compilation object doesn't actually work. It works _only_ if there's another client running at the same time, e. g. `bloop compile --watch`.

**Comment by odisseus** [comment]
It looks like the duplicated error message appears when the method `fury.core.FuryBuildClient#onBuildPublishDiagnostics` is called the second time. As far as I know, this means that Bloop actually sends the diagnostic message for the errors that have been already fixed. Interestingly, this doesn't happen with the Bloop's own watcher.

**Comment by odisseus** [comment]
This problem doesn't appear with the latest version of Bloop ([`e94b10c`](https://github.com/scalacenter/bloop/commit/e94b10c3241f904487ce1602f17482ae9a6ca787)).

**Comment by odisseus** [comment]
Partially fixed by PR #949.

**Comment by propensive** [comment]
What's the current status on this, @odisseus? I haven't noticed it recently, but I'm far from certain it's fixed...

**Comment by odisseus** [comment]
I haven't worked on this issue since PR #949.

I believe its cause lies in the way Bloop handles its own caches, although I haven't completed the investigation. It seems that when the Bloop client is terminated and reconnected, the server sends it the diagnostic messages from the last compilation requested by the previous instance of the client. This happens even if the code has been changed while the client was disconnected and the diagnostics might have become outdated.

Pull request #949 sidestepped this problem by extending the lifetime of the Bloop client over multiple compile requests. However, the problem might be still present when Fury is launched in standalone mode.

**Comment by propensive** [comment]
I haven't seen this particular problem for a while, so I'm closing this issue.
